# Change these first
owner: phpMyFAQ
repo: status.phpmyfaq.de

# Add your sites here
sites:
  - name: phpMyFAQ Homepage
    url: https://www.phpmyfaq.de
  - name: phpMyFAQ API
    url: https://api.phpmyfaq.de/versions
  - name: Password Hash Generator Tool
    url: https://password.phpmyfaq.de

status-website:
  cname: status.phpmyfaq.de
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: phpMyFAQ Status
  introTitle: "**phpMyFAQ** status"
  introMessage: Status of phpMyFAQ servicess
  navbar:
    - title: phpMyFAQ Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
